const LABELS = {
    addToCalendar: 'Adauga in Google Calendar',
    addDocument: 'Adauga un document de tipul asta.',
    addDocumetTitle: 'Adauga un nou document',
    addDocumetDescription:
        'Adauga documentul tau. Incepe experienta prin alegerea tipului',
    addANewCar: 'Adaugă o nouă mașină.',
    addPart: 'Adaugare piesa',
    addPartDescription:
        'Avem nevoie de urmatoarele detalii pentru a retine piesa pe care o ai.',
    appTitle: 'gasestepiesa.online',
    authFailed: 'Autentificare nereusita, incercati mai tarziu.',
    beginDate: 'Data inceput',
    carUpdated: 'Detaliile masinii au fost actualizate cu success.',
    cancel: 'Anulare',
    createPart: 'Crează o piesă nouă.',
    chooseDocumentDescription: `Alege un tip de document, incarca-l si apasa pe detectarea textului.
    La final, verifica corectitudinea datelor si salveaza datele. Se va seta
    automat in calendarul tau Google un nou eveniment.`,
    detailsAbout: 'Detalii legate despre',
    deleteItemMessage: 'Are you sure you want to delete this item?',
    detectionSuccess: 'Detectia textului a fost realizata cu succes.',
    documentDeleted: 'Document deleted with success',
    documentType: 'Tipul documentului',
    documentsCosts: 'Costurile documentelor',
    edit: 'Actualizeaza',
    editDocumentTitle: 'Editeaza documentul ales',
    editDocumetDescription: 'Editeaza documentul tau. Ai ales documentul:',
    editCarsDetails: 'Editeaza informatiile despre masina ta.',
    expired: 'A expirat pe ',
    expiredDocuments: 'Documente expirate',
    expirationDate: 'Data expirare',
    forbiddenMessage: 'S-a produs o eroare. Autentificati-va inca o data.',
    home: 'Acasa',
    itp: 'ITP',
    manualData: 'Introducerea manuala a datelor ',
    notExisting: 'Nu exista',
    noDataAvailable: 'Nu exista date',
    noPartFound: 'Nu există date.',
    save: 'Salvare',
    sendToDetect: 'Detecteaza',
    seeCalendarEvent: 'Vezi evenimentul in google calendar',
    price: 'Pret',
    rca: 'RCA',
    rovigneta: 'Rovigneta',
    update: 'Update',
    updatePart: 'Editare piesa',
    updatePartDescription:
        'Avem nevoie de urmatoarele detalii pentru a modifica piesa pe care o ai.',
    usersWithSamePart: 'Utilizatori care au aceeasi piesa',
    willExpire: 'Va expira in ',
    yourPart: 'Piesa ta'
};

export { LABELS };
